name: build_docker_image

on:
  workflow_run:
    workflows: [ "release" ]
    types:
      - completed

jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: docker login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "davidsmith3" --password-stdin

      - name: docker/setup-qemu-action@v3
        uses: docker/setup-qemu-action@v3

      - name: docker/setup-buildx-action@v3
        uses: docker/setup-buildx-action@v3

      - name: docker buildx build
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t "davidsmith3/spapi-tokens-cli" \
            --push \
            .